apiVersion: v1
kind: Service
metadata:
  name: carsite-service
  namespace: car-site
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: car-site-server
  ports:
  - name: car-site-server
    protocol: TCP
    port: 80
    targetPort: 80