apiVersion: v1
kind: Service
metadata:
  name: carsite-service
  namespace: car-site
  labels:
    app: car-site-server
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: car-site-server
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
