apiVersion: apps/v1
kind: Deployment
metadata:
  name: car-site-server
  namespace: car-site
spec:
  replicas: 2
  selector:
    matchLabels:
      app: car-site-server
  template:
    metadata:
      labels:
        app: car-site-server
    spec:
      containers:
        - name: car-site
          image: ladudarko/car-site:3.0
      ports:
        - containerPort: 8080
